apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: groovy-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://devops:3000/Ismaeil/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: devops
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
